apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - ../base/podinfo
patchesStrategicMerge:
  - podinfo-values.yaml
patches:
- path: patch-sec.yaml
  target:
    kind: Deployment
    labelSelector: "app.kubernetes.io/name=podinfo"
